# Generated by Django 2.1.7 on 2020-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200120_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_No', models.IntegerField(default=True)),
                ('Shipping_Adress', models.CharField(default=True, max_length=500)),
                ('Type_Of_Payment', models.CharField(choices=[('credit card', 'credit card'), ('Cash On Delivery', 'Cash On Delivery'), ('Online Transactions', 'Online Transactions')], default='', max_length=200)),
            ],
        ),
    ]
