# Generated by Django 2.1.7 on 2020-01-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
