# Generated by Django 2.1.7 on 2020-01-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200114_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
