# Generated by Django 2.1.7 on 2020-01-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_paren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='paren',
        ),
    ]
