# Generated by Django 2.1.7 on 2020-01-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_remove_comment_parentt'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
