# Generated by Django 2.1.7 on 2020-01-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_comment_parentt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parentt',
            new_name='parent',
        ),
    ]
