# Generated by Django 2.1.7 on 2019-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191216_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
