# Generated by Django 2.1.7 on 2019-12-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191231_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk', 'image', '-published_date', '-updated', '-timestamp']},
        ),
    ]
