# Generated by Django 2.1.7 on 2020-01-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='price',
        ),
    ]
