# Generated by Django 2.1.7 on 2020-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogpost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='username',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
