# Generated by Django 2.1.7 on 2020-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200105_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='username',
            field=models.CharField(max_length=120, verbose_name='auth.User'),
        ),
    ]
