# Generated by Django 2.1.7 on 2020-01-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200105_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk', 'image']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='username',
        ),
    ]
