# Generated by Django 2.1.7 on 2020-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200106_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='catogory',
            field=models.CharField(choices=[('leash', 'LEASH'), ('chains', 'CHAINS'), ('food', 'FOOD'), ('CHEW', 'chew')], default='chains', max_length=120),
        ),
    ]
