# Generated by Django 2.1.7 on 2020-01-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_blogpost_catogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user',
            new_name='shop_name',
        ),
    ]
