# Generated by Django 2.1.7 on 2020-01-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200108_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='unique_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='landmark',
            field=models.CharField(default=True, max_length=340),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='mobile_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='shop_adress',
            field=models.CharField(default=True, max_length=220),
        ),
    ]
