# Generated by Django 2.1.7 on 2020-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200115_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='catogory',
            field=models.CharField(choices=[('leash', 'LEASH'), ('chains', 'CHAINS'), ('food', 'FOOD'), ('CHEW', 'chew')], default='', max_length=120),
        ),
    ]
