# Generated by Django 2.1.7 on 2020-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200115_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/'),
        ),
    ]
