# Generated by Django 2.1.7 on 2020-01-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200115_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='MinOffer',
            field=models.IntegerField(default=True),
        ),
    ]
