# Generated by Django 2.1.7 on 2020-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_blogpost_minoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
